aws_region="eu-west-2"
stack="terraform-case"
fargate-task-service-role="terraform-case-role"
aws_ecr="app"
aws_profile="default"
source_repo_name="app"
source_repo_branch="main"
image_repo_name="app"