name: Terraform Deployment
on:
 push:
   branches: [main]
 pull_request:
   branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: eu-west-2

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5

    - name: Export AWS credentials
      run: |
        echo "export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "export AWS_DEFAULT_REGION=us-west-2" >> $GITHUB_ENV
        sed -i 's/username = "DUMMYUSER"/username = "${{ secrets.DB_USERNAME }}"/' ./terraform/parameters.tf
        sed -i 's/password = "DUMMYPASS"/password = "${{ secrets.DB_PASSWORD }}"/' ./terraform/parameters.tf

    - name: Terraform Init and Apply for Infra
      run: |
        cd ./terraform
        terraform init
        terraform destroy -auto-approve